# Generated by Django 4.2.4 on 2023-10-06 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(max_length=1000, null=True)),
                ('time_created', models.DateTimeField(default=datetime.datetime(2023, 10, 6, 11, 17, 50, 437736))),
            ],
        ),
    ]
